### ISSUE TITLE
acloader.cm package conflict

### ISSUE THREAD

**Issue by duncr** [docura-io/vscode-cm#25]
When used in an extension that already has references to `cm.io` and `cm.runtime` a compile error occurs.

Suggest either checking if they are already referenced prior to insertion, or simply relocating the `use` statements inside the code block.

**Comment by kaestlyn** [comment]
Seem's like in cmUtil.packageFileUsings isn't finding them in the package.cm file for some reason, possibly regex would need some tweaks.

I didn't know you could put them inside the code block, I'll just move them there to avoid this altogether, much cleaner solution.

**Comment by kaestlyn** [comment]
Looks like it's probably the regex test, a temp fix is make sure in your `package.cm` file you don't have any extra spaces or anything around the line, the regex is expecting end of line following the `;`

``` java
use cm.io;
use cm.runtime;
```

**Comment by kaestlyn** [comment]
This is fixed in version 0.2.3.  The extenion is now on the VSCode Marketplace (much easier to update, and you'll be notified when there are updates thru vscode).

To update, remove the old extension:
- F1 -> Show Installed Extensions
- Click the X next to the CM extension
- Restart VS Code
- Ctrl+P
- Type `ext install cm` (don't hit enter, wait for the list to load)
- Scroll down to the bottom and pick CM
- Wait for it to install, and restart VSCode when prompted.

In the future, the little extension icon on the bottom left of the toolbar will let you know when there are updates to the extension.
