### ISSUE TITLE
Repo structure causing "cm.start not found"

### ISSUE THREAD

**Issue by eddievf** [docura-io/vscode-cm#54]
`Command "cm.start" not found` when trying to `CM: Start CM` after the switch to Git workspace. I'm guessing it has something to do with the new folder structure that has the  `home` folder as empty and moved most things to `base`.

I'm wondering where to change the path to look in `base` instead of `home`.

**Comment by kaestlyn** [comment]
I can see a few places I'll need to make some tweaks. We aren't using GIT workspaces yet. I cant get my 10.0 git workspace to even start CM, Ill try to get that going so I can get a quick fix out for you.

**Comment by eddievf** [comment]
Using the Operator? I went with the "vanilla instructions" (at least to get going) and had to personally switch to the version10.0 branch on the base repo to get it running.

Really appreciate the quick response, Tyler. No rush (:

**Comment by kaestlyn** [comment]
Yeah -  I had to re-clone the BASE folder, somehow mine was messed up.  I'm hoping I can get a demo/beta for you to try either later tonight or tomorrow morning.  I have it working here now, I just need to do some cleanup.  I'll let you know when I post the BETA VSIX (VSCode extension file) on here with some directions on how to apply it to test. (Since we aren't really using GIT in operator yet, I can't test with much)

**Comment by kaestlyn** [comment]
I've posted a beta release on the releases page: https://github.com/docura-io/vscode-cm/releases/tag/v1.4.0-beta.  You'll have to manually install it.  Let me know how it works for you.

**Comment by eddievf** [comment]
Installed the beta and it seems to be working pretty well. 
Thanks for the quick assistance, Tyler! I'll let you know if i end up running into anything.

**Comment by kaestlyn** [comment]
It seems it has a problem at the moment with the logic that auto fills the package name for you on files, so just be careful until I get that fixed, it keeps putting the file URL instead of the package name, so you'll end up with something like:

`package c:\cetdev\version10.0\personal\lambt\whatever.something`

This is triggered when a file is created / moved while VSCode is open.

**Comment by kaestlyn** [comment]
@eddievf - I've put up a new Beta: https://github.com/docura-io/vscode-cm/releases/tag/v1.4.0-beta2  It should fix the package name autofill when creating / moving files.
