### ISSUE TITLE
Autocompile

### ISSUE THREAD

**Issue by fpmalard** [docura-io/vscode-cm#58]
Hello,

In version 1.4.2, whenever you perform a PASTE command in current CM file, it triggers the compilation process.

Is there a way to disable this?

Thank you.

**Comment by kaestlyn** [comment]
I think this is a result of VSCode invoking "Go to definition" when you press the control key and have your mouse cursor over some code
I've been watching https://github.com/microsoft/vscode/issues/3130 for a long time in hopes they will allow customization of this behavior.  
I've just got in the habit of flicking my mouse out after clicking to avoid this.  If anyone knows more about the VSCode apis on how we could avoid this I'd be happy to entertain ideas.

**Comment by kaestlyn** [comment]
@fpmalard - I did discover a way to work around this.  VSCode lets you swap the multi-cursor modifier key, so if you do this it will make it so that ALT becomes the key you would have to hold (or hold and click) to trigger the mouse gesture for go to definition.  Only downside is if you use multi-cursor a lot it will take a little getting used to since this makes `CTRL` be the key to insert them now.  

Anyways, if you update your settings.json file you can make it so you only do this swap in CM files:

```json
"[cm]": {
        "editor.multiCursorModifier": "ctrlCmd"
}
```

**Comment by kaestlyn** [comment]
It seems they don't want to give us a way to customize this behavior, so given we have a decent work around, I'm going to close this issue.  If Microsoft ever does give the ability to customize the mouse behavior more, I will be sure to call it out in a setup guide.
