### ISSUE TITLE
Syntax Highlight "and" "or"

### ISSUE THREAD

**Issue by menghif** [docura-io/vscode-cm#89]
"and" and "or" are highlighted even when part of other words:

![image](https://user-images.githubusercontent.com/53121061/234079366-53c802b5-d031-44ee-89bd-5d3a625fa468.png)

https://github.com/docura-io/vscode-cm/blob/548c39837c2755955f1d4da01a0cbab5db0540be/syntaxes/cm.tmLanguage.json#L842
I think you can just put spaces in this regex like this:
`"match": "\\b(?: and | or )\\b"` 

I wasn't able to run the extension locally so I couldn't test this.

**Comment by kaestlyn** [comment]
I really need to get the instructions updated on how to develop this repo. Sorry about that! 

Have you turned on the "New Syntax" setting for the extension?

![image](https://user-images.githubusercontent.com/1458549/234088098-1efde2fe-43dc-45fd-aeb4-71ff67e54848.png)

If you have not, then it's actually using the `CM.plist` file instead of the `cm.tmLanguage.json`

If you ARE using that I've added some notes below:

That is very strange, I'll have to poke and see, but the `\b` before and after the capture group should force word boundaries:

Without `\b`
![image](https://user-images.githubusercontent.com/1458549/234087482-4bdd4dcd-fc28-4b8c-8331-a30faeaa1ef4.png)

With `\b`:
![image](https://user-images.githubusercontent.com/1458549/234087555-4151790a-f5d6-4836-a896-4fff9a80be17.png)

If you want to experiment with this file, I believe you can navigate to where you vscode installs your extensions (in my case its in my user folder in a folder called `.vscode` and then go to `.vscode\extensions\docuraio.cm-1.x.x\syntaxes` (the 1.x.x will depend on the version you have installed)

**Comment by menghif** [comment]
That makes sense, I wasn't using the New Syntax. A big thank you for the extension! It's great to be coding in VS Code again.

**Comment by kaestlyn** [comment]
It's not 100%, but its much better than the original one I had.  Slowly working on correcting it but its a battle.
